build:
	dotnet build
clean:
	dotnet clean
restore:
	dotnet restore
watch:
	dotnet watch --project ./src/UI/UserManagementApi/UserManagementApi.csproj run
start:
	dotnet run --project ./src/UI/UserManagementApi/UserManagementApi.csproj --launch-provile 'Development'